FROM quay.io/keycloak/keycloak:26.2 AS builder
ENV KC_DB=dev-file KC_HEALTH_ENABLED=true KC_HTTP_ENABLED=true KC_PROXY_HEADERS=xforwarded KC_HOSTNAME_STRICT=false KC_CACHE=local KC_HTTP_MANAGEMENT_ENABLED=false
RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/
COPY ./keycloak/realm.json /opt/keycloak/data/import/realm.json
ENV KC_DB=dev-file KC_HEALTH_ENABLED=true KC_HTTP_ENABLED=true KC_PROXY_HEADERS=xforwarded KC_HOSTNAME_STRICT=false KC_CACHE=local KC_HTTP_MANAGEMENT_ENABLED=false
